const ERROR_CODE = 400;
const SERVER_ERROR = 500;
const ERROR_NOT_FOUND = 404;
const OK = 200;
const CREATED_OK = 201;
const UNAUTHORIZED_ERROR = 401;

module.exports = {
  ERROR_CODE, SERVER_ERROR, ERROR_NOT_FOUND, OK, CREATED_OK, UNAUTHORIZED_ERROR,
};
